/**
 * DO NOT EDIT - This file is auto-generated by Supabase CLI
 * 
 * Re-generate command:
 *   npx supabase gen types typescript --project-id xnxdvvakgdoanhbqwoyk --schema public > src/types/database.ts
 * 
 * After regeneration, add back the convenience types at the bottom of this file.
 * 
 * Last generated: 2026-01-11
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      ai_regen_jobs: {
        Row: {
          compilation_id: string
          completed_at: string | null
          created_at: string | null
          id: string
          options: Json | null
          result_paragraph_id: string | null
          status: string
          target_chapter_id: string | null
          target_paragraph_id: string | null
        }
        Insert: {
          compilation_id: string
          completed_at?: string | null
          created_at?: string | null
          id?: string
          options?: Json | null
          result_paragraph_id?: string | null
          status?: string
          target_chapter_id?: string | null
          target_paragraph_id?: string | null
        }
        Update: {
          compilation_id?: string
          completed_at?: string | null
          created_at?: string | null
          id?: string
          options?: Json | null
          result_paragraph_id?: string | null
          status?: string
          target_chapter_id?: string | null
          target_paragraph_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_regen_jobs_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_regen_jobs_result_paragraph_id_fkey"
            columns: ["result_paragraph_id"]
            isOneToOne: false
            referencedRelation: "compiled_paragraphs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_regen_jobs_target_chapter_id_fkey"
            columns: ["target_chapter_id"]
            isOneToOne: false
            referencedRelation: "compiled_chapters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_regen_jobs_target_paragraph_id_fkey"
            columns: ["target_paragraph_id"]
            isOneToOne: false
            referencedRelation: "compiled_paragraphs"
            referencedColumns: ["id"]
          },
        ]
      }
      analytics_events: {
        Row: {
          actor_type: string
          created_at: string
          event_data: Json
          event_name: string
          id: string
          respondent_token_hash: string | null
          session_id: string | null
          user_id: string | null
        }
        Insert: {
          actor_type: string
          created_at?: string
          event_data: Json
          event_name: string
          id?: string
          respondent_token_hash?: string | null
          session_id?: string | null
          user_id?: string | null
        }
        Update: {
          actor_type?: string
          created_at?: string
          event_data?: Json
          event_name?: string
          id?: string
          respondent_token_hash?: string | null
          session_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "analytics_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analytics_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chapters: {
        Row: {
          content: string | null
          created_at: string | null
          deleted_at: string | null
          id: string
          order_index: number
          output_draft_id: string
          source_message_ids: Json | null
          title: string | null
          updated_at: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          deleted_at?: string | null
          id?: string
          order_index: number
          output_draft_id: string
          source_message_ids?: Json | null
          title?: string | null
          updated_at?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          deleted_at?: string | null
          id?: string
          order_index?: number
          output_draft_id?: string
          source_message_ids?: Json | null
          title?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "chapters_output_draft_id_fkey"
            columns: ["output_draft_id"]
            isOneToOne: false
            referencedRelation: "output_drafts"
            referencedColumns: ["id"]
          },
        ]
      }
      claim_logs: {
        Row: {
          changed_by: string | null
          claim_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["claim_status"] | null
          id: string
          note: string | null
          to_status: Database["public"]["Enums"]["claim_status"]
        }
        Insert: {
          changed_by?: string | null
          claim_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["claim_status"] | null
          id?: string
          note?: string | null
          to_status: Database["public"]["Enums"]["claim_status"]
        }
        Update: {
          changed_by?: string | null
          claim_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["claim_status"] | null
          id?: string
          note?: string | null
          to_status?: Database["public"]["Enums"]["claim_status"]
        }
        Relationships: [
          {
            foreignKeyName: "claim_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "claim_logs_claim_id_fkey"
            columns: ["claim_id"]
            isOneToOne: false
            referencedRelation: "claims"
            referencedColumns: ["id"]
          },
        ]
      }
      claims: {
        Row: {
          attachments: Json | null
          compensation_amount: number | null
          compensation_type: string | null
          created_at: string
          description: string
          id: string
          order_id: string
          resolution: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: Database["public"]["Enums"]["claim_status"]
          type: Database["public"]["Enums"]["claim_type"]
          updated_at: string
        }
        Insert: {
          attachments?: Json | null
          compensation_amount?: number | null
          compensation_type?: string | null
          created_at?: string
          description: string
          id?: string
          order_id: string
          resolution?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["claim_status"]
          type: Database["public"]["Enums"]["claim_type"]
          updated_at?: string
        }
        Update: {
          attachments?: Json | null
          compensation_amount?: number | null
          compensation_type?: string | null
          created_at?: string
          description?: string
          id?: string
          order_id?: string
          resolution?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["claim_status"]
          type?: Database["public"]["Enums"]["claim_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "claims_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "claims_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      compilation_episode_inclusions: {
        Row: {
          compilation_id: string
          decision_reason: string | null
          episode_id: string
          id: string
          inclusion_status: Database["public"]["Enums"]["episode_inclusion"]
          signals: Json | null
        }
        Insert: {
          compilation_id: string
          decision_reason?: string | null
          episode_id: string
          id?: string
          inclusion_status: Database["public"]["Enums"]["episode_inclusion"]
          signals?: Json | null
        }
        Update: {
          compilation_id?: string
          decision_reason?: string | null
          episode_id?: string
          id?: string
          inclusion_status?: Database["public"]["Enums"]["episode_inclusion"]
          signals?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "compilation_episode_inclusions_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compilation_episode_inclusions_episode_id_fkey"
            columns: ["episode_id"]
            isOneToOne: false
            referencedRelation: "episodes"
            referencedColumns: ["id"]
          },
        ]
      }
      compilations: {
        Row: {
          chapter_count_max: number | null
          chapter_count_min: number | null
          completed_at: string | null
          created_at: string | null
          editor_notes: string | null
          error_detail: Json | null
          error_message: string | null
          id: string
          idempotency_key: string | null
          intent: string
          paragraphs_per_chapter_max: number | null
          paragraphs_per_chapter_min: number | null
          pdf_confirmed_at: string | null
          pdf_confirmed_by: string | null
          pdf_snapshot_at: string | null
          pdf_snapshot_version: number | null
          preferred_structure: string | null
          progress: Json | null
          result_meta: Json | null
          review_status: Database["public"]["Enums"]["review_status"]
          session_id: string
          status: string
          version: number
        }
        Insert: {
          chapter_count_max?: number | null
          chapter_count_min?: number | null
          completed_at?: string | null
          created_at?: string | null
          editor_notes?: string | null
          error_detail?: Json | null
          error_message?: string | null
          id?: string
          idempotency_key?: string | null
          intent: string
          paragraphs_per_chapter_max?: number | null
          paragraphs_per_chapter_min?: number | null
          pdf_confirmed_at?: string | null
          pdf_confirmed_by?: string | null
          pdf_snapshot_at?: string | null
          pdf_snapshot_version?: number | null
          preferred_structure?: string | null
          progress?: Json | null
          result_meta?: Json | null
          review_status?: Database["public"]["Enums"]["review_status"]
          session_id: string
          status?: string
          version: number
        }
        Update: {
          chapter_count_max?: number | null
          chapter_count_min?: number | null
          completed_at?: string | null
          created_at?: string | null
          editor_notes?: string | null
          error_detail?: Json | null
          error_message?: string | null
          id?: string
          idempotency_key?: string | null
          intent?: string
          paragraphs_per_chapter_max?: number | null
          paragraphs_per_chapter_min?: number | null
          pdf_confirmed_at?: string | null
          pdf_confirmed_by?: string | null
          pdf_snapshot_at?: string | null
          pdf_snapshot_version?: number | null
          preferred_structure?: string | null
          progress?: Json | null
          result_meta?: Json | null
          review_status?: Database["public"]["Enums"]["review_status"]
          session_id?: string
          status?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "compilations_pdf_confirmed_by_fkey"
            columns: ["pdf_confirmed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compilations_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      compiled_chapters: {
        Row: {
          compilation_id: string
          created_at: string | null
          id: string
          order_index: number
          title: string
          updated_at: string | null
        }
        Insert: {
          compilation_id: string
          created_at?: string | null
          id?: string
          order_index: number
          title: string
          updated_at?: string | null
        }
        Update: {
          compilation_id?: string
          created_at?: string | null
          id?: string
          order_index?: number
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "compiled_chapters_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
        ]
      }
      compiled_paragraph_edits: {
        Row: {
          after_content: string | null
          before_content: string | null
          created_at: string | null
          edit_reason: string | null
          edited_by_type: string
          edited_by_user_id: string | null
          id: string
          paragraph_id: string
        }
        Insert: {
          after_content?: string | null
          before_content?: string | null
          created_at?: string | null
          edit_reason?: string | null
          edited_by_type: string
          edited_by_user_id?: string | null
          id?: string
          paragraph_id: string
        }
        Update: {
          after_content?: string | null
          before_content?: string | null
          created_at?: string | null
          edit_reason?: string | null
          edited_by_type?: string
          edited_by_user_id?: string | null
          id?: string
          paragraph_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "compiled_paragraph_edits_edited_by_user_id_fkey"
            columns: ["edited_by_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compiled_paragraph_edits_paragraph_id_fkey"
            columns: ["paragraph_id"]
            isOneToOne: false
            referencedRelation: "compiled_paragraphs"
            referencedColumns: ["id"]
          },
        ]
      }
      compiled_paragraph_snapshots: {
        Row: {
          chapter_order_index: number
          compilation_id: string
          content: string
          created_at: string
          id: string
          is_hidden: boolean
          paragraph_id: string
          paragraph_order_index: number
          paragraph_type: string
          pdf_snapshot_version: number
        }
        Insert: {
          chapter_order_index: number
          compilation_id: string
          content: string
          created_at?: string
          id?: string
          is_hidden: boolean
          paragraph_id: string
          paragraph_order_index: number
          paragraph_type: string
          pdf_snapshot_version: number
        }
        Update: {
          chapter_order_index?: number
          compilation_id?: string
          content?: string
          created_at?: string
          id?: string
          is_hidden?: boolean
          paragraph_id?: string
          paragraph_order_index?: number
          paragraph_type?: string
          pdf_snapshot_version?: number
        }
        Relationships: [
          {
            foreignKeyName: "compiled_paragraph_snapshots_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compiled_paragraph_snapshots_paragraph_id_fkey"
            columns: ["paragraph_id"]
            isOneToOne: false
            referencedRelation: "compiled_paragraphs"
            referencedColumns: ["id"]
          },
        ]
      }
      compiled_paragraph_sources: {
        Row: {
          episode_id: string
          id: string
          message_ids: string[]
          paragraph_id: string
        }
        Insert: {
          episode_id: string
          id?: string
          message_ids?: string[]
          paragraph_id: string
        }
        Update: {
          episode_id?: string
          id?: string
          message_ids?: string[]
          paragraph_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "compiled_paragraph_sources_episode_id_fkey"
            columns: ["episode_id"]
            isOneToOne: false
            referencedRelation: "episodes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compiled_paragraph_sources_paragraph_id_fkey"
            columns: ["paragraph_id"]
            isOneToOne: false
            referencedRelation: "compiled_paragraphs"
            referencedColumns: ["id"]
          },
        ]
      }
      compiled_paragraphs: {
        Row: {
          chapter_id: string
          content: string
          created_at: string | null
          id: string
          is_hidden: boolean
          order_index: number
          paragraph_type: string
          revision: number
          updated_at: string | null
        }
        Insert: {
          chapter_id: string
          content: string
          created_at?: string | null
          id?: string
          is_hidden?: boolean
          order_index: number
          paragraph_type?: string
          revision?: number
          updated_at?: string | null
        }
        Update: {
          chapter_id?: string
          content?: string
          created_at?: string | null
          id?: string
          is_hidden?: boolean
          order_index?: number
          paragraph_type?: string
          revision?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "compiled_paragraphs_chapter_id_fkey"
            columns: ["chapter_id"]
            isOneToOne: false
            referencedRelation: "compiled_chapters"
            referencedColumns: ["id"]
          },
        ]
      }
      context_snapshots: {
        Row: {
          created_at: string | null
          emotional_moments: Json | null
          id: string
          is_current: boolean
          key_facts: Json | null
          last_message_id: string | null
          next_topic_suggestion: string | null
          session_id: string
          topics_covered: Json | null
          topics_remaining: Json | null
          updated_at: string | null
          version: number
        }
        Insert: {
          created_at?: string | null
          emotional_moments?: Json | null
          id?: string
          is_current?: boolean
          key_facts?: Json | null
          last_message_id?: string | null
          next_topic_suggestion?: string | null
          session_id: string
          topics_covered?: Json | null
          topics_remaining?: Json | null
          updated_at?: string | null
          version?: number
        }
        Update: {
          created_at?: string | null
          emotional_moments?: Json | null
          id?: string
          is_current?: boolean
          key_facts?: Json | null
          last_message_id?: string | null
          next_topic_suggestion?: string | null
          session_id?: string
          topics_covered?: Json | null
          topics_remaining?: Json | null
          updated_at?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "context_snapshots_last_message_id_fkey"
            columns: ["last_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "context_snapshots_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      edit_history: {
        Row: {
          after_content: string | null
          before_content: string | null
          chapter_id: string
          created_at: string | null
          deleted_at: string | null
          edited_by: Database["public"]["Enums"]["editor_type"]
          id: string
        }
        Insert: {
          after_content?: string | null
          before_content?: string | null
          chapter_id: string
          created_at?: string | null
          deleted_at?: string | null
          edited_by: Database["public"]["Enums"]["editor_type"]
          id?: string
        }
        Update: {
          after_content?: string | null
          before_content?: string | null
          chapter_id?: string
          created_at?: string | null
          deleted_at?: string | null
          edited_by?: Database["public"]["Enums"]["editor_type"]
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "edit_history_chapter_id_fkey"
            columns: ["chapter_id"]
            isOneToOne: false
            referencedRelation: "chapters"
            referencedColumns: ["id"]
          },
        ]
      }
      emotional_events: {
        Row: {
          confidence: number | null
          context_snapshot_id: string | null
          created_at: string | null
          detected_emotion: string
          id: string
          message_id: string
          session_id: string
        }
        Insert: {
          confidence?: number | null
          context_snapshot_id?: string | null
          created_at?: string | null
          detected_emotion: string
          id?: string
          message_id: string
          session_id: string
        }
        Update: {
          confidence?: number | null
          context_snapshot_id?: string | null
          created_at?: string | null
          detected_emotion?: string
          id?: string
          message_id?: string
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "emotional_events_context_snapshot_id_fkey"
            columns: ["context_snapshot_id"]
            isOneToOne: false
            referencedRelation: "context_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "emotional_events_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "emotional_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      episodes: {
        Row: {
          content: string | null
          created_at: string | null
          emotional_weight: number | null
          has_reflection: boolean | null
          has_turning_point: boolean | null
          id: string
          inclusion_status: Database["public"]["Enums"]["episode_inclusion"]
          order_index: number
          session_id: string
          source_message_ids: string[]
          summary: string
          theme: Database["public"]["Enums"]["episode_theme"]
          time_period: string | null
          title: string | null
          updated_at: string | null
        }
        Insert: {
          content?: string | null
          created_at?: string | null
          emotional_weight?: number | null
          has_reflection?: boolean | null
          has_turning_point?: boolean | null
          id?: string
          inclusion_status?: Database["public"]["Enums"]["episode_inclusion"]
          order_index: number
          session_id: string
          source_message_ids?: string[]
          summary: string
          theme: Database["public"]["Enums"]["episode_theme"]
          time_period?: string | null
          title?: string | null
          updated_at?: string | null
        }
        Update: {
          content?: string | null
          created_at?: string | null
          emotional_weight?: number | null
          has_reflection?: boolean | null
          has_turning_point?: boolean | null
          id?: string
          inclusion_status?: Database["public"]["Enums"]["episode_inclusion"]
          order_index?: number
          session_id?: string
          source_message_ids?: string[]
          summary?: string
          theme?: Database["public"]["Enums"]["episode_theme"]
          time_period?: string | null
          title?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "episodes_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      message_edit_logs: {
        Row: {
          after_content: string
          before_content: string
          edit_type: string
          edited_at: string
          edited_by: string
          id: string
          message_id: string
          session_id: string
        }
        Insert: {
          after_content: string
          before_content: string
          edit_type: string
          edited_at?: string
          edited_by: string
          id?: string
          message_id: string
          session_id: string
        }
        Update: {
          after_content?: string
          before_content?: string
          edit_type?: string
          edited_at?: string
          edited_by?: string
          id?: string
          message_id?: string
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "message_edit_logs_edited_by_fkey"
            columns: ["edited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_edit_logs_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_edit_logs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          audio_url: string | null
          content: string
          created_at: string | null
          deleted_at: string | null
          id: string
          input_type: Database["public"]["Enums"]["input_type"] | null
          meta: Json | null
          order_index: number
          role: Database["public"]["Enums"]["message_role"]
          session_id: string
        }
        Insert: {
          audio_url?: string | null
          content: string
          created_at?: string | null
          deleted_at?: string | null
          id?: string
          input_type?: Database["public"]["Enums"]["input_type"] | null
          meta?: Json | null
          order_index: number
          role: Database["public"]["Enums"]["message_role"]
          session_id: string
        }
        Update: {
          audio_url?: string | null
          content?: string
          created_at?: string | null
          deleted_at?: string | null
          id?: string
          input_type?: Database["public"]["Enums"]["input_type"] | null
          meta?: Json | null
          order_index?: number
          role?: Database["public"]["Enums"]["message_role"]
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      order_status_logs: {
        Row: {
          changed_by: string | null
          created_at: string
          from_status: Database["public"]["Enums"]["order_status"] | null
          id: string
          metadata: Json | null
          order_id: string
          reason: string | null
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["order_status"] | null
          id?: string
          metadata?: Json | null
          order_id: string
          reason?: string | null
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["order_status"] | null
          id?: string
          metadata?: Json | null
          order_id?: string
          reason?: string | null
          to_status?: Database["public"]["Enums"]["order_status"]
        }
        Relationships: [
          {
            foreignKeyName: "order_status_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_status_logs_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          amount: number
          archive_estimated_seconds: number | null
          archive_generated_at: string | null
          archive_progress: number | null
          archive_started_at: string | null
          archive_status: string | null
          archive_url: string | null
          cancel_reason: string | null
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          dedication: string | null
          dedication_generated_at: string | null
          dedication_generation_cost: number | null
          dedication_suggestions: Json | null
          delivered_at: string | null
          id: string
          is_active: boolean
          package: Database["public"]["Enums"]["package_type"]
          paid_at: string | null
          payment_method: Database["public"]["Enums"]["payment_method"] | null
          payment_note: string | null
          payment_requested_at: string | null
          progress: Json | null
          recipient_name: string | null
          refund_amount: number | null
          refund_reason: string | null
          refunded_at: string | null
          session_id: string
          shipped_at: string | null
          shipping_address: string | null
          shipping_phone: string | null
          status: Database["public"]["Enums"]["order_status"]
          tracking_carrier: string | null
          tracking_number: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          archive_estimated_seconds?: number | null
          archive_generated_at?: string | null
          archive_progress?: number | null
          archive_started_at?: string | null
          archive_status?: string | null
          archive_url?: string | null
          cancel_reason?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          dedication?: string | null
          dedication_generated_at?: string | null
          dedication_generation_cost?: number | null
          dedication_suggestions?: Json | null
          delivered_at?: string | null
          id?: string
          is_active?: boolean
          package: Database["public"]["Enums"]["package_type"]
          paid_at?: string | null
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          payment_note?: string | null
          payment_requested_at?: string | null
          progress?: Json | null
          recipient_name?: string | null
          refund_amount?: number | null
          refund_reason?: string | null
          refunded_at?: string | null
          session_id: string
          shipped_at?: string | null
          shipping_address?: string | null
          shipping_phone?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          amount?: number
          archive_estimated_seconds?: number | null
          archive_generated_at?: string | null
          archive_progress?: number | null
          archive_started_at?: string | null
          archive_status?: string | null
          archive_url?: string | null
          cancel_reason?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          dedication?: string | null
          dedication_generated_at?: string | null
          dedication_generation_cost?: number | null
          dedication_suggestions?: Json | null
          delivered_at?: string | null
          id?: string
          is_active?: boolean
          package?: Database["public"]["Enums"]["package_type"]
          paid_at?: string | null
          payment_method?: Database["public"]["Enums"]["payment_method"] | null
          payment_note?: string | null
          payment_requested_at?: string | null
          progress?: Json | null
          recipient_name?: string | null
          refund_amount?: number | null
          refund_reason?: string | null
          refunded_at?: string | null
          session_id?: string
          shipped_at?: string | null
          shipping_address?: string | null
          shipping_phone?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      output_drafts: {
        Row: {
          created_at: string | null
          fingerprint_message_count: number | null
          fingerprint_message_id: string | null
          id: string
          locked_at: string | null
          session_id: string
          status: Database["public"]["Enums"]["output_status"] | null
          title: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          fingerprint_message_count?: number | null
          fingerprint_message_id?: string | null
          id?: string
          locked_at?: string | null
          session_id: string
          status?: Database["public"]["Enums"]["output_status"] | null
          title?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          fingerprint_message_count?: number | null
          fingerprint_message_id?: string | null
          id?: string
          locked_at?: string | null
          session_id?: string
          status?: Database["public"]["Enums"]["output_status"] | null
          title?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "output_drafts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      print_order_logs: {
        Row: {
          changed_by: string | null
          created_at: string
          from_status: Database["public"]["Enums"]["print_order_status"] | null
          id: string
          note: string | null
          print_order_id: string
          to_status: Database["public"]["Enums"]["print_order_status"]
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["print_order_status"] | null
          id?: string
          note?: string | null
          print_order_id: string
          to_status: Database["public"]["Enums"]["print_order_status"]
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["print_order_status"] | null
          id?: string
          note?: string | null
          print_order_id?: string
          to_status?: Database["public"]["Enums"]["print_order_status"]
        }
        Relationships: [
          {
            foreignKeyName: "print_order_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "print_order_logs_print_order_id_fkey"
            columns: ["print_order_id"]
            isOneToOne: false
            referencedRelation: "print_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      print_orders: {
        Row: {
          admin_note: string | null
          claim_opened_at: string | null
          claim_reason: string | null
          claim_resolution: string | null
          claim_resolved_at: string | null
          compilation_id: string
          created_at: string
          delivered_at: string | null
          id: string
          postal_code: string
          processed_by: string | null
          recipient_name: string
          recipient_phone: string
          shipped_at: string | null
          shipping_address: string
          shipping_address_detail: string | null
          status: Database["public"]["Enums"]["print_order_status"]
          tracking_carrier: string | null
          tracking_number: string | null
          updated_at: string
        }
        Insert: {
          admin_note?: string | null
          claim_opened_at?: string | null
          claim_reason?: string | null
          claim_resolution?: string | null
          claim_resolved_at?: string | null
          compilation_id: string
          created_at?: string
          delivered_at?: string | null
          id?: string
          postal_code: string
          processed_by?: string | null
          recipient_name: string
          recipient_phone: string
          shipped_at?: string | null
          shipping_address: string
          shipping_address_detail?: string | null
          status?: Database["public"]["Enums"]["print_order_status"]
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
        }
        Update: {
          admin_note?: string | null
          claim_opened_at?: string | null
          claim_reason?: string | null
          claim_resolution?: string | null
          claim_resolved_at?: string | null
          compilation_id?: string
          created_at?: string
          delivered_at?: string | null
          id?: string
          postal_code?: string
          processed_by?: string | null
          recipient_name?: string
          recipient_phone?: string
          shipped_at?: string | null
          shipping_address?: string
          shipping_address_detail?: string | null
          status?: Database["public"]["Enums"]["print_order_status"]
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "print_orders_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "print_orders_processed_by_fkey"
            columns: ["processed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      respondent_message_edit_logs: {
        Row: {
          after_content: string
          before_content: string
          edit_type: string
          edited_at: string
          id: string
          message_id: string
          session_id: string
          share_token_hash: string
        }
        Insert: {
          after_content: string
          before_content: string
          edit_type: string
          edited_at?: string
          id?: string
          message_id: string
          session_id: string
          share_token_hash: string
        }
        Update: {
          after_content?: string
          before_content?: string
          edit_type?: string
          edited_at?: string
          id?: string
          message_id?: string
          session_id?: string
          share_token_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: "respondent_message_edit_logs_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "respondent_message_edit_logs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      review_status_logs: {
        Row: {
          changed_by: string | null
          changed_by_type: Database["public"]["Enums"]["changed_by_type"]
          compilation_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["review_status"] | null
          id: string
          reason: string | null
          to_status: Database["public"]["Enums"]["review_status"]
        }
        Insert: {
          changed_by?: string | null
          changed_by_type: Database["public"]["Enums"]["changed_by_type"]
          compilation_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["review_status"] | null
          id?: string
          reason?: string | null
          to_status: Database["public"]["Enums"]["review_status"]
        }
        Update: {
          changed_by?: string | null
          changed_by_type?: Database["public"]["Enums"]["changed_by_type"]
          compilation_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["review_status"] | null
          id?: string
          reason?: string | null
          to_status?: Database["public"]["Enums"]["review_status"]
        }
        Relationships: [
          {
            foreignKeyName: "review_status_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_status_logs_compilation_id_fkey"
            columns: ["compilation_id"]
            isOneToOne: false
            referencedRelation: "compilations"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          created_at: string | null
          id: string
          interview_state: Json | null
          mode: Database["public"]["Enums"]["session_mode"] | null
          mode_config: Json | null
          share_token: string | null
          share_token_expires_at: string | null
          status: Database["public"]["Enums"]["session_status"] | null
          subject_name: string
          subject_relation: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          interview_state?: Json | null
          mode?: Database["public"]["Enums"]["session_mode"] | null
          mode_config?: Json | null
          share_token?: string | null
          share_token_expires_at?: string | null
          status?: Database["public"]["Enums"]["session_status"] | null
          subject_name: string
          subject_relation: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          interview_state?: Json | null
          mode?: Database["public"]["Enums"]["session_mode"] | null
          mode_config?: Json | null
          share_token?: string | null
          share_token_expires_at?: string | null
          status?: Database["public"]["Enums"]["session_status"] | null
          subject_name?: string
          subject_relation?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string | null
          email: string
          id: string
          name: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          name?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          name?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_payment_gate: { Args: { p_session_id: string }; Returns: boolean }
      create_context_snapshot: {
        Args: {
          p_emotional_moments: Json
          p_key_facts: Json
          p_last_message_id: string
          p_next_topic_suggestion: string
          p_session_id: string
          p_topics_covered: Json
          p_topics_remaining: Json
        }
        Returns: string
      }
      edit_last_message_by_token: {
        Args: { p_new_content: string; p_token: string; p_token_secret: string }
        Returns: {
          error_message: string
          message_id: string
          should_regenerate: boolean
          success: boolean
        }[]
      }
      get_messages_by_token: {
        Args: { p_token: string }
        Returns: {
          content: string
          created_at: string
          id: string
          input_type: Database["public"]["Enums"]["input_type"]
          order_index: number
          role: Database["public"]["Enums"]["message_role"]
        }[]
      }
      get_my_active_order: {
        Args: { p_session_id: string }
        Returns: {
          amount: number
          cancel_reason: string | null
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          delivered_at: string | null
          id: string
          is_active: boolean
          package: Database["public"]["Enums"]["package_type"]
          paid_at: string | null
          payment_method: Database["public"]["Enums"]["payment_method"] | null
          payment_note: string | null
          payment_requested_at: string | null
          progress: Json | null
          recipient_name: string | null
          refund_amount: number | null
          refund_reason: string | null
          refunded_at: string | null
          session_id: string
          shipped_at: string | null
          shipping_address: string | null
          shipping_phone: string | null
          status: Database["public"]["Enums"]["order_status"]
          tracking_carrier: string | null
          tracking_number: string | null
          updated_at: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "orders"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      get_session_by_share_token: {
        Args: { p_token: string }
        Returns: {
          id: string
          mode: Database["public"]["Enums"]["session_mode"]
          mode_config: Json
          status: Database["public"]["Enums"]["session_status"]
          subject_name: string
          subject_relation: string
        }[]
      }
      insert_message_by_token: {
        Args: {
          p_audio_url?: string
          p_content: string
          p_input_type?: Database["public"]["Enums"]["input_type"]
          p_role: Database["public"]["Enums"]["message_role"]
          p_token: string
        }
        Returns: string
      }
      is_admin: { Args: never; Returns: boolean }
      is_valid_order_transition: {
        Args: {
          p_from: Database["public"]["Enums"]["order_status"]
          p_to: Database["public"]["Enums"]["order_status"]
        }
        Returns: boolean
      }
      transition_order_status: {
        Args: {
          p_metadata?: Json
          p_new_status: Database["public"]["Enums"]["order_status"]
          p_order_id: string
          p_reason?: string
        }
        Returns: {
          amount: number
          cancel_reason: string | null
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          delivered_at: string | null
          id: string
          is_active: boolean
          package: Database["public"]["Enums"]["package_type"]
          paid_at: string | null
          payment_method: Database["public"]["Enums"]["payment_method"] | null
          payment_note: string | null
          payment_requested_at: string | null
          progress: Json | null
          recipient_name: string | null
          refund_amount: number | null
          refund_reason: string | null
          refunded_at: string | null
          session_id: string
          shipped_at: string | null
          shipping_address: string | null
          shipping_phone: string | null
          status: Database["public"]["Enums"]["order_status"]
          tracking_carrier: string | null
          tracking_number: string | null
          updated_at: string
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "orders"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      validate_final_compilation_grounding: {
        Args: { p_compilation_id: string }
        Returns: undefined
      }
    }
    Enums: {
      changed_by_type: "user" | "system" | "admin"
      claim_status: "opened" | "in_review" | "resolved" | "rejected"
      claim_type:
        | "print_defect"
        | "shipping_damage"
        | "wrong_delivery"
        | "content_error"
        | "other"
      editor_type: "child" | "ai"
      episode_inclusion:
        | "candidate"
        | "core"
        | "supporting"
        | "appendix"
        | "excluded"
      episode_theme:
        | "childhood"
        | "adolescence"
        | "early_adulthood"
        | "career"
        | "marriage"
        | "parenting"
        | "turning_point"
        | "hardship"
        | "joy"
        | "reflection"
        | "legacy"
      input_type: "text" | "voice"
      message_role: "ai" | "user"
      order_status:
        | "pending_payment"
        | "paid"
        | "in_production"
        | "ready_to_ship"
        | "shipped"
        | "delivered"
        | "completed"
        | "refunded"
        | "cancelled"
        | "expired"
      output_status: "draft" | "reviewed" | "finalized" | "locked"
      package_type: "pdf_only" | "standard" | "premium"
      payment_method: "manual" | "toss" | "kakao" | "card"
      print_order_status:
        | "pending"
        | "printing"
        | "shipped"
        | "delivered"
        | "claim_opened"
        | "claim_resolved"
      review_status:
        | "pending_review"
        | "needs_fixes"
        | "approved_for_edit"
        | "approved_for_pdf"
        | "approved_for_print"
        | "printed"
        | "print_failed"
      session_mode: "relaxed" | "dday" | "together"
      session_status: "draft" | "in_progress" | "completed"
      user_role: "user" | "admin" | "operator"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      changed_by_type: ["user", "system", "admin"],
      claim_status: ["opened", "in_review", "resolved", "rejected"],
      claim_type: [
        "print_defect",
        "shipping_damage",
        "wrong_delivery",
        "content_error",
        "other",
      ],
      editor_type: ["child", "ai"],
      episode_inclusion: [
        "candidate",
        "core",
        "supporting",
        "appendix",
        "excluded",
      ],
      episode_theme: [
        "childhood",
        "adolescence",
        "early_adulthood",
        "career",
        "marriage",
        "parenting",
        "turning_point",
        "hardship",
        "joy",
        "reflection",
        "legacy",
      ],
      input_type: ["text", "voice"],
      message_role: ["ai", "user"],
      order_status: [
        "pending_payment",
        "paid",
        "in_production",
        "ready_to_ship",
        "shipped",
        "delivered",
        "completed",
        "refunded",
        "cancelled",
        "expired",
      ],
      output_status: ["draft", "reviewed", "finalized", "locked"],
      package_type: ["pdf_only", "standard", "premium"],
      payment_method: ["manual", "toss", "kakao", "card"],
      print_order_status: [
        "pending",
        "printing",
        "shipped",
        "delivered",
        "claim_opened",
        "claim_resolved",
      ],
      review_status: [
        "pending_review",
        "needs_fixes",
        "approved_for_edit",
        "approved_for_pdf",
        "approved_for_print",
        "printed",
        "print_failed",
      ],
      session_mode: ["relaxed", "dday", "together"],
      session_status: ["draft", "in_progress", "completed"],
      user_role: ["user", "admin", "operator"],
    },
  },
} as const

// ============================================================
// Convenience type aliases (add back after regeneration)
// ============================================================

// Enum type aliases for backward compatibility
export type SessionStatus = Database['public']['Enums']['session_status']
export type SessionMode = Database['public']['Enums']['session_mode']
export type MessageRole = Database['public']['Enums']['message_role']
export type InputType = Database['public']['Enums']['input_type']
export type OutputStatus = Database['public']['Enums']['output_status']
export type EditorType = Database['public']['Enums']['editor_type']
export type EpisodeTheme = Database['public']['Enums']['episode_theme']
export type EpisodeInclusion = Database['public']['Enums']['episode_inclusion']
export type ReviewStatus = Database['public']['Enums']['review_status']
export type ChangedByType = Database['public']['Enums']['changed_by_type']
export type UserRole = Database['public']['Enums']['user_role']
export type PrintOrderStatus = Database['public']['Enums']['print_order_status']
export type PackageType = Database['public']['Enums']['package_type']
export type OrderStatus = Database['public']['Enums']['order_status']
export type PaymentMethod = Database['public']['Enums']['payment_method']
export type ClaimStatus = Database['public']['Enums']['claim_status']
export type ClaimType = Database['public']['Enums']['claim_type']

// String-based types (not enums in DB, but typed as string)
export type CompilationIntent = 'preview' | 'final'
export type CompilationStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled'
export type ParagraphType = 'grounded' | 'connector' | 'editorial' | 'intro' | 'outro'

// Alias for backward compatibility
export type OrderPaymentStatus = OrderStatus

// Table row type aliases
export type User = Tables<'users'>
export type Session = Tables<'sessions'>
export type Message = Tables<'messages'>
export type ContextSnapshot = Tables<'context_snapshots'>
export type EmotionalEvent = Tables<'emotional_events'>
export type OutputDraft = Tables<'output_drafts'>
export type Chapter = Tables<'chapters'>
export type EditHistory = Tables<'edit_history'>
export type Episode = Tables<'episodes'>
export type Compilation = Tables<'compilations'>
export type CompiledChapter = Tables<'compiled_chapters'>
export type CompiledParagraph = Tables<'compiled_paragraphs'>
export type CompiledParagraphSource = Tables<'compiled_paragraph_sources'>
export type CompiledParagraphEdit = Tables<'compiled_paragraph_edits'>
export type CompiledParagraphSnapshot = Tables<'compiled_paragraph_snapshots'>
export type AiRegenJob = Tables<'ai_regen_jobs'>
export type ReviewStatusLog = Tables<'review_status_logs'>
export type PrintOrder = Tables<'print_orders'>
export type Order = Tables<'orders'>
export type OrderStatusLog = Tables<'order_status_logs'>
export type Claim = Tables<'claims'>
export type ClaimLog = Tables<'claim_logs'>

// ============================================================
// DOTTING v1.2 → v1.3: 멀티모달 메시지 타입 확장
// 용어 정제: "보물(Treasure)" → "간직할 순간(Moment)"
// ============================================================

/**
 * 간직할 순간(Moment) 메타데이터 (v1.3 신규)
 * 
 * 철학: "순간(Moment)"은 DOTTING의 점(●) 아이덴티티와 연결
 * - 하나의 점 = 하나의 순간
 * - 순간들이 모여 선(이야기)이 됨
 * - 브랜드 메시지: "모든 이야기는 계속됩니다"
 */
export interface MomentMetadata {
  /** 간직할 순간 여부 */
  is_moment?: boolean
  
  /** 순간 순서 (1부터 시작) */
  moment_index?: number
  
  /** 표시 시각 (ISO 8601) */
  moment_marked_at?: string
  
  /** 사용자 지정 제목 (선택) */
  moment_title?: string
}

/**
 * 보물(Treasure) 메타데이터 (v1.2 레거시)
 * @deprecated v1.3부터 MomentMetadata 사용 권장
 * 
 * 하위 호환성을 위해 유지되며, normalizeMomentData()로 자동 변환됨
 */
export interface TreasureMetadata {
  /** @deprecated Use MomentMetadata.is_moment */
  is_treasure?: boolean
  
  /** @deprecated Use MomentMetadata.moment_index */
  treasure_index?: number
  
  /** @deprecated Use MomentMetadata.moment_marked_at */
  marked_at?: string
}

/**
 * 오디오 메타데이터
 * - duration: 오디오 길이 (초)
 * - waveform: 파형 데이터 (0~1 사이 값의 배열, 최대 50개)
 */
export interface AudioMetadata {
  /** 오디오 길이 (초) */
  duration?: number
  
  /** 파형 데이터 (0~1 사이 값, 최대 50개) */
  waveform?: number[]
  
  /** @deprecated v1.2에서 제거됨. MomentMetadata.is_moment 사용 */
  is_highlight?: boolean
}

/**
 * 확장된 메시지 메타데이터 타입
 * - messages.meta JSON 필드의 타입 안전성 확보
 * - 신규(Moment) + 레거시(Treasure) 필드 모두 지원
 */
export interface MessageMetadata 
  extends MomentMetadata, 
          TreasureMetadata, 
          AudioMetadata {
  [key: string]: unknown
}

/**
 * 유니버설 메시지 타입
 * - 텍스트/음성 하이브리드 지원
 * - content: 항상 존재 (음성의 경우 STT 결과 또는 요약)
 * - audio_url: 음성 메시지인 경우에만 존재
 */
export type UniversalMessage = Message & {
  meta?: MessageMetadata
}

// ============================================================
// 유틸리티 함수: 레거시 데이터 정규화
// ============================================================

/**
 * 레거시 Treasure 데이터를 Moment 형식으로 정규화
 * 
 * 사용 예시:
 * ```typescript
 * const moment = normalizeMomentData(message.meta)
 * if (moment.is_moment) {
 *   console.log(`순간 ${moment.moment_index}`)
 * }
 * ```
 * 
 * @param meta - 메시지 메타데이터 (nullable)
 * @returns 정규화된 MomentMetadata
 */
export function normalizeMomentData(meta?: MessageMetadata): MomentMetadata {
  if (!meta) return {}
  
  return {
    is_moment: meta.is_moment ?? meta.is_treasure,
    moment_index: meta.moment_index ?? meta.treasure_index,
    moment_marked_at: meta.moment_marked_at ?? meta.marked_at,
    moment_title: meta.moment_title,
  }
}

/**
 * 메시지가 "간직할 순간"인지 확인
 * 
 * @param message - 확인할 메시지
 * @returns 간직할 순간 여부
 */
export function isMoment(message: UniversalMessage): boolean {
  const moment = normalizeMomentData(message.meta)
  return moment.is_moment === true
}

/**
 * 메시지 배열을 순간 순서대로 정렬
 * 
 * @param messages - 정렬할 메시지 배열
 * @returns moment_index 기준 오름차순 정렬된 배열
 */
export function sortByMomentIndex(messages: UniversalMessage[]): UniversalMessage[] {
  return [...messages].sort((a, b) => {
    const momentA = normalizeMomentData(a.meta)
    const momentB = normalizeMomentData(b.meta)
    
    const indexA = momentA.moment_index ?? 0
    const indexB = momentB.moment_index ?? 0
    
    return indexA - indexB
  })
}

// Insert type aliases
export type InsertTables<T extends keyof Database['public']['Tables']> = 
  Database['public']['Tables'][T]['Insert']

// Update type aliases
export type UpdateTables<T extends keyof Database['public']['Tables']> = 
  Database['public']['Tables'][T]['Update']
